FROM node:22-alpine

WORKDIR /monorepo

COPY . .

RUN ls -al

RUN npm install -g @nrwl/cli && npm install
RUN npx nx reset
# RUN npx nx build nurish-api

ENTRYPOINT ["npx", "nx", "serve", "nurish-api", "--prod"]

